"""Initial migration

Revision ID: 545fe12e5059
Revises: 
Create Date: 2025-05-08 11:54:18.668365

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '545fe12e5059'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # First, create the vector extension
    op.execute('CREATE EXTENSION IF NOT EXISTS vector;')
    
    # Create tables
    op.create_table('source',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_id'), 'source', ['id'], unique=False)
    
    # Create article table without vector column first
    op.create_table('article',
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('raw_json', sa.JSON(), nullable=True),
    sa.Column('image_url', sa.String(length=2048), nullable=True),
    sa.Column('industry', sa.String(length=50), nullable=True),
    sa.Column('relevance_score', sa.Float(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['source.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url'),
    sa.UniqueConstraint('url', name='unique_article_url')
    )
    
    # Add vector column separately using SQL
    op.execute('ALTER TABLE article ADD COLUMN embedding vector(3072);')
    
    op.create_index(op.f('ix_article_id'), 'article', ['id'], unique=False)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_article_id'), table_name='article')
    op.drop_table('article')
    op.drop_index(op.f('ix_source_id'), table_name='source')
    op.drop_table('source')
    # ### end Alembic commands ###